// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayerRepository;

#nullable disable

namespace NLayerRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231213121657_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Core.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kalemler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kitaplar "
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Defterler"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("E_Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            E_Mail = "john.doe@example.com",
                            Name = "John",
                            PhoneNumber = 123456789,
                            SurName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            E_Mail = "jane.smith@example.com",
                            Name = "Jane",
                            PhoneNumber = 987654321,
                            SurName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            E_Mail = "alice.johnson@example.com",
                            Name = "Alice",
                            PhoneNumber = 555555555,
                            SurName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            E_Mail = "bob.williams@example.com",
                            Name = "Bob",
                            PhoneNumber = 777777777,
                            SurName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            E_Mail = "eve.taylor@example.com",
                            Name = "Eve",
                            PhoneNumber = 999999999,
                            SurName = "Taylor"
                        },
                        new
                        {
                            Id = 6,
                            E_Mail = "michael.johnson@example.com",
                            Name = "Michael",
                            PhoneNumber = 111111111,
                            SurName = "Johnson"
                        },
                        new
                        {
                            Id = 7,
                            E_Mail = "emily.davis@example.com",
                            Name = "Emily",
                            PhoneNumber = 222222222,
                            SurName = "Davis"
                        },
                        new
                        {
                            Id = 8,
                            E_Mail = "daniel.brown@example.com",
                            Name = "Daniel",
                            PhoneNumber = 333333333,
                            SurName = "Brown"
                        },
                        new
                        {
                            Id = 9,
                            E_Mail = "olivia.miller@example.com",
                            Name = "Olivia",
                            PhoneNumber = 444444444,
                            SurName = "Miller"
                        },
                        new
                        {
                            Id = 10,
                            E_Mail = "william.clark@example.com",
                            Name = "William",
                            PhoneNumber = 555555555,
                            SurName = "Clark"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.50m,
                            Date = new DateTime(2023, 12, 13, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6228),
                            PaymentMethod = "Kredi Kartı",
                            TransactionId = "ABC123"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50.75m,
                            Date = new DateTime(2023, 12, 11, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6240),
                            PaymentMethod = "Nakit",
                            TransactionId = "XYZ789"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200.00m,
                            Date = new DateTime(2023, 12, 8, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6244),
                            PaymentMethod = "Havale",
                            TransactionId = "DEF456"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 75.25m,
                            Date = new DateTime(2023, 12, 12, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6245),
                            PaymentMethod = "Kripto Para",
                            TransactionId = "GHI789"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 120.90m,
                            Date = new DateTime(2023, 12, 10, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6246),
                            PaymentMethod = "Çek",
                            TransactionId = "JKL012"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 85.60m,
                            Date = new DateTime(2023, 12, 9, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6247),
                            PaymentMethod = "Banka Kartı",
                            TransactionId = "MNO345"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 150.25m,
                            Date = new DateTime(2023, 12, 7, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6248),
                            PaymentMethod = "EFT",
                            TransactionId = "PQR678"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 60.30m,
                            Date = new DateTime(2023, 12, 6, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6249),
                            PaymentMethod = "Sanal Cüzdan",
                            TransactionId = "STU901"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 40.15m,
                            Date = new DateTime(2023, 12, 5, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6250),
                            PaymentMethod = "Mobil Ödeme",
                            TransactionId = "VWX234"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 110.75m,
                            Date = new DateTime(2023, 12, 4, 15, 16, 57, 216, DateTimeKind.Local).AddTicks(6251),
                            PaymentMethod = "Fatura Ödeme",
                            TransactionId = "YZA567"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 13, 15, 16, 57, 217, DateTimeKind.Local).AddTicks(776),
                            Name = "Kalem 1",
                            Price = 100m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 13, 15, 16, 57, 217, DateTimeKind.Local).AddTicks(781),
                            Name = "Kalem 2",
                            Price = 200m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 13, 15, 16, 57, 217, DateTimeKind.Local).AddTicks(782),
                            Name = "Kalem 3",
                            Price = 600m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 12, 13, 15, 16, 57, 217, DateTimeKind.Local).AddTicks(783),
                            Name = "Kiataplar 1",
                            Price = 680m,
                            Stock = 26
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 12, 13, 15, 16, 57, 217, DateTimeKind.Local).AddTicks(784),
                            Name = "Kitaplar 2",
                            Price = 650m,
                            Stock = 320
                        });
                });

            modelBuilder.Entity("NLayer.Core.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Kırmızı",
                            Height = 100,
                            ProductId = 1,
                            Width = 200
                        },
                        new
                        {
                            Id = 2,
                            Color = "Mavi",
                            Height = 300,
                            ProductId = 2,
                            Width = 500
                        });
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.HasOne("NLayer.Core.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.ProductFeature", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
